mqtt:
  broker: your.mqtt.ip.address
  port: 1883
  client_id: home-assistant-1
  username: YOURUSERNAME
  password: YOURPASSWORD


light:
  - platform: mqtt_json
    name: "SN1 LED"
    state_topic: "digisense-9ADE8A/extLED1/state"
    command_topic: "digisense-9ADE8A/extLED1/set"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
    retain: true


sensor:
  - platform: mqtt
    state_topic: "digisense-9ADE8A/humid/state"
    name: "SN1 Humidity"
    unit_of_measurement: "%"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "digisense-9ADE8A/lux/state"
    name: "SN1 Lux"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "digisense-9ADE8A/temp/state"
    name: "SN1 Temperature"
    unit_of_measurement: "°F"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "digisense-9ADE8A/feel/state"
    name: "SN1 Real Feel"
    unit_of_measurement: "°F"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"


binary_sensor:
  - platform: mqtt
    state_topic: "digisense-9ADE8A/pir/state"
    name: "SN1 PIR"
    payload_on: "YES"
    payload_off: "NO"
    device_class: motion
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "digisense-9ADE8A/but1/state"
    name: "SN1 Button1"
    payload_on: "1"
    payload_off: "0"
    availability_topic: "digisense-9ADE8A/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"


group:
  sensor_node_1_card:
    name: Sensor Node 1
    entities:
      - light.sn1_led
      - sensor.sn1_temperature
      - sensor.sn1_humidity
      - sensor.sn1_lux
      - binary_sensor.sn1_pir
      - sensor.sn1_real_feel
      - binary_sensor.sn1_button1
